### PR TITLE
Fixes #103 - Text Overflow in Show Pages

### LINKED ISSUE #103: Longer words flow out of the text box
Many 'show' pages display the text without hyphenating the longer words. 
screen shot 2016-02-09 at 1 00 42 am

### PR DESCRIPTION
**Pull request by adityathiru**
* Fixes #103

### CODE REVIEW

**Comment by adityathiru** [comment]
@prachi1210 Sure ma'am. I'll look into it and send another commit to this same branch.

**Comment by prachi1210** [comment]
Also you don't need to remove whitespaces but remove any changes in your code that changes code linting unless there were serious code quality issues in the previous commit.

**Comment by adityathiru** [comment]
* The initial commit was like that, because the code wasn't readable, with all the css in one line. It was inconsistent compared to the style in which it was written before.
* In the second commit, I followed what was given in the link and applied a patch and reset the styling format.
* Actually, just one line was added. As the initial code wasn't readable, I formatted it in such a manner. No code linting issues.

**Comment by adityathiru** [comment]
I'll amend the commits from next time. Thanks for the tip!

**Comment by prachi1210** [comment]
@adityathiru I meant this 
image

In any case, I am approving the changes as of now. Please take care of this in the future.

**Comment by adityathiru** [comment]
Sorry ma'am. Sure, I'll take care of that in the future.

**Pull request merged**
