### PR TITLE
PLT#98 | Fix close button for alerts.

### LINKED ISSUE #98: Alert close button not working
screen shot 2016-01-28 at 12 11 20 pm

The cross provided on right top corner for closing the alert message is not working. Such error messages are used on all forms.

### PR DESCRIPTION
**Pull request by ishit**
- Fix #98

### CODE REVIEW

**Comment by shubhpatel108** [comment]
@ishit, this leaves the "ErrorExplanation" div after the error has been deleted. Hence, a red box will still be visible on the page.
screen shot 2016-03-07 at 1 51 45 am

**Comment by ishit** [comment]
Thanks for pointing it out. Fixed it.

**Comment by prachisinghania** [comment]
Hello,
I am intersted in working for Systers's Peace Cops Project on Photo Languge
Translation (Ruby on Rails).
How should I contact and discuss about the project.

**Comment by navya-nizamkari** [comment]
Hi  @prachisinghania , you can contact and talk about the project on the project's slack channel at : https://systers-opensource.slack.com/messages/language-translation/
There is also channel for general doubts : https://systers-opensource.slack.com/messages/general/

**Pull request merged**
