### PR TITLE
17-change pagination functionality to kaminari

### PR DESCRIPTION
**Pull request by isuriupeksha**
Pagination gem has been changed, #17

### CODE REVIEW

**Comment by wonook** [comment]
I've run the application myself, but found out that it's complaining and not showing the views. Since we're going to use ReactJS, maybe it would be a good idea to just take them off rather than to migrate to `kaminari`.

**Comment by isuriupeksha** [comment]
@wonook but you we will need some meta data to make the pagination section work with ReactJS.

**Comment by isuriupeksha** [comment]
http://codeloveandboards.com/blog/2014/10/06/rails-and-react-iii-parent-child-communication/

**Comment by wonook** [comment]
Alright, the article's way seems fine. We'll have to use that article as a reference.

**Comment by wonook** [comment]
Are you done with the implementation for this PR?

**Comment by isuriupeksha** [comment]
I will try to do myself. But still learning CoffeeScript.

**Comment by wonook** [comment]
Alright. Try to get the merge conflicts ASAP for this PR.
I think it would be better to merge #53 first, because this PR includes changes in Gemfile.lock. Take a look at #53 it's not too long.

**Comment by rosariorobinson** [comment]
@azelma can you review this PR?

**Comment by azelma** [comment]
Are the other gemfile changes related to compatibility with kaminari? If not, it might be good to split those out.

**Comment by wonook** [comment]
I agree with @azelma . You might have run `$ bundle update` at some point but you should check if things are deprecated if you're going to upgrade the gems, so probably it would be better to do it as an another issue.

**Comment by isuriupeksha** [comment]
@wonook merged with the `develop` branch. Lets finish ReactJS integration in a next PR.

**Pull request merged**
