### PR TITLE
Merge develop branch to master

### PR DESCRIPTION
**Pull request by prachi1210**
### Checklist

- [x] I read the [contributing guide](/CONTRIBUTING.md) and I've followed it.
- [x] Commit message gives complete and useful information about the changes under it.
- [x] I ran the code locally and checked for common errors and uncaught exceptions.
- [x] My code is unit testable.

After you submit your pull request, DO NOT close it or click 'Update Branch'.

Occasionally, you may be asked to rebase your branch.

### CODE REVIEW

**Comment by prachi1210** [comment]
@adityathiru @Anjali05 I noticed that the develop branch has not been merged into master for a very long time. I'd need help resolving merge conflicts.

**Comment by adityathiru** [comment]
@prachi1210 Sure ma'am. I'll look into it 👍

**Comment by prachi1210** [comment]
@adityathiru @Anjali05 @MeepyMay I am merging this branch into master and tagging it as alpha version of release. We can work on making it stable in phase 3. Is that okay with you guys?

**Comment by adityathiru** [comment]
@prachi1210 That is fine with me ma'am !

**Pull request merged**
