### PR TITLE
Plt#33-1 Completed test cases for category controller

### PR DESCRIPTION
**Pull request by isuriupeksha**
-- Add more test cases for category controller.
-- Add flash message for create, update and deleted

### CODE REVIEW

**Comment by wonook** [comment]
One sec, this PR doesn't have the rebasing applied on it (#34). This is probably going to bring a LOT of confusion in its git history. I recommend branching out of the current `develop` branch again and doing whatever you have to do from there.

**Comment by wonook** [comment]
Anyways I thought that you were done with #33 on #34, and you've said so on Slack.

**Comment by isuriupeksha** [comment]
@wonook This is something additional refactoring and adding more test cases to the each controllers. Since you have done the role system, we have to add more test cases by user role. So it would be great add more test cases when we have a time.

**Comment by isuriupeksha** [comment]
closing this one.

**Pull request closed without merging**
