### PR TITLE
Template integration, refactoring and search functionality integration

### PR DESCRIPTION
**Pull request by isuriupeksha**
Following changes are done 

1. Integration custom template (this is for Temporary fix. Later we can integrated new template according to the new UI design) 
2. Refactoring user role system
3. Integrated pg_search functionality for `User` and `Article` models. 
4. Added pagination for user and article records

### CODE REVIEW

**Comment by isuriupeksha** [comment]
@SaumyaGurtu 
Here is my first design https://github.com/systers/language-translation/blob/gsoc15_isuri/docs/design/photos.png

But I am waiting for the feedback for next iterative. I am suppose to show to both `english` and `phonetic` text in a card.

**Comment by wonook** [comment]
I've included comments on your commits, take a look. 
Most of them are advices to squash commits that I thought belonged to the same set of jobs. Refer to [this site](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) if you need help with rewriting history.
I've also added questions - take a look at them as well.

**Comment by wonook** [comment]
Hi @isuriupeksha , you're pushing commits here, but haven't provided any responses to my comments. Did you have a look at them?

**Comment by wonook** [comment]
okay, I'm out of patience. I'll just do the squashing myself and push it onto this branch if there still aren't any responses in an hour. You know that you're not the only one working on the project.

**Pull request merged**
