### PR TITLE
Adds backup script

### PR DESCRIPTION
**Pull request by adityathiru**
* Adds necessary commands which needs to be executed for setting up a backup server.
* Supports multiple secondary servers and smtp based mail notifications in case of failure.

### Checklist

- [x] I read the [contributing guide](/CONTRIBUTING.md) and I've followed it.
- [x] Commit message gives complete and useful information about the changes under it.
- [x] I ran the code locally and checked for common errors and uncaught exceptions.
- [x] My code is unit testable.

After you submit your pull request, DO NOT close it or click 'Update Branch'.

Occasionally, you may be asked to rebase your branch.

### CODE REVIEW

**Comment by adityathiru** [comment]
@prachi1210 I talked to Nithya ma'am about this. I'll modify this commit according to the changes suggested. Apparently the vm is backed up regularly. Hence we need to set up only a db back for PLT itself, which I'm currently working on.

**Comment by prachi1210** [comment]
Okay, I am marking this as WIP then

**Comment by adityathiru** [comment]
Sure ma'am. Once I get the server details, I'll update the setup and inform you about the same.

**Comment by adityathiru** [comment]
@prachi1210 I checked with Julia regarding this. The code I've submitted in this PR will be the final version. I've added a README file on how to go about with setting it up too on the production server.

**Pull request merged**
