### PR TITLE
#99-Fix menu button for mobile view

### PR DESCRIPTION
**Pull request by shubhpatel108**
@isuriupeksha I have figured out the problem. The script for enabling the button, unlike other scripts, needs to be loaded after the page body.

### CODE REVIEW

**Comment by rosariorobinson** [comment]
@isuriupeksha @abelards are you both okay with this PR?

**Comment by abelards** [comment]
I'm not sure why it would work better by just changing this, since the jQuery observer didn't change?
But if it didn't work and now works please do :)

**Comment by isuriupeksha** [comment]
@shubhpatel108 @abelards We should convert that JS script to using jQuery. I remember, I couldn't rewrite it again.

**Comment by abelards** [comment]
Sure, feel free! As long as it's adding simplicity and consistency I'll always be up for it :)

**Pull request merged**
