### PR TITLE
Fixes for upgrading rails version

### LINKED ISSUE #18: Fixes for upgrading rails version
There had been some changes in upgrading Rails from 4.1 to 4.2 that haven't yet been applied to the application. I'll apply these changes to our application.

### PR DESCRIPTION
**Pull request by wonook**
Issue #18 - Fixes for upgrading rails version

1.Specify the ruby-version
2.Update old gems and Rails
3.Update deprecated configs and syntaxes
4.Set up `.travis.yml` and `database.yml.travis` for CI.
5.Show travis status on README

Author : @wonook - Won Wook SONG (wsong0512@gmail.com)

This pull request closes #18 

---
Please add this message upon merging this PR, so that we can see a summary of each PR on our commit history

like this: Imgur

### CODE REVIEW

**Comment by wonook** [comment]
@abelards, please provide your feedbacks here!

**Comment by abelards** [comment]
Looks like there are a few problems with routing at least.
Let's fix that and remove `Gemfile.lock` before merging :)

**Comment by abelards** [comment]
Looks like there are a few problems with routing at least.
Let's fix that and remove `Gemfile.lock` before merging :)

**Comment by abelards** [comment]
:+1: 
After discussion on Gemfile.lock [1] and seeing the tests will soon be fixed by Isuri I'm OK for the merge.

[1] http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore

**Comment by wonook** [comment]
Merci @abelards! I'll merge this PR.

**Pull request merged**
